verbs: ../../spanish/spanish-verbs/matched-verbs.csv
nouns: ../../spanish/spanish-nouns/matched-nouns.csv
transitivities: ../../spanish/transitivity/ancora-rae/merged-transitivities.csv
determiners: ../../spanish/spanish-determiners/determiners.csv
pronouns: ../../spanish/spanish-pronouns/pronouns.csv
output: ../grammar-files/g6/feature-grammar.txt
