verbs: ../../spanish/freeling-espanol/all.verbs.csv
nouns: ../../spanish/freeling-espanol/MM.nom.csv
transitivities: ../../spanish/transitivity/ancora-rae/merged-transitivities.csv
determiners: ../../spanish/spanish-determiners/determiners-sorted.csv
pronouns: ../../spanish/spanish-pronouns/pronouns.csv
adpositions: ../../guarani/adpositions/adpositions.csv
adjectives: ../../spanish/freeling-espanol/MM.adj.csv
output: ../grammar-files/g11-adj/feature-grammar.txt