verbs: ../../guarani/verbs/matched-verbs-guarani.csv
nouns: ../../guarani/nouns/finished-nouns.csv
transitivities: ../../spanish/transitivity/ancora-rae/merged-transitivities.csv
determiners: ../../spanish/spanish-determiners/determiners.csv
pronouns: ../../spanish/spanish-pronouns/pronouns.csv
adpositions: ../../guarani/adpositions/adpositions.csv
output: ../grammar-files/g10/feature-grammar.txt